06-module
js-tasks-ru/jsbasic-20240520_y-dudar pull request #8
Opened 2024-06-21 21:12 UTC by KMS56135

2024-06-21 21:13 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-06-23 15:11 UTC, SinimaWath requested changes

2024-06-23 15:11 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    slides[0].addEventListener('load', () => {
Нет необходимости использовать событие load.

Чтобы решить проблему, того что offsetWidth = 0, это свойство надо получать в момент, когда кликают на стрелки.


`carouselMove.offsetWidth` в момент клика

2024-06-23 15:43 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-06-24 11:04 UTC, SinimaWath approved these changes

2024-06-24 11:05 UTC, merged